import type {Metadata} from 'next';
import {Vazirmatn} from 'next/font/google';
import {cookies} from 'next/headers';

import {CookieName, ThemeType} from '@/constants';
import {MainProviders} from '@/providers';

import '@/styles/globals.css';

const vazirmatn = Vazirmatn({
  weight: ['300', '400', '600'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  const cookieStore = cookies();
  const theme = cookieStore.get(CookieName.THEME);

  return (
    <html lang='fa' dir='rtl' data-color-mode={theme?.value}>
      <body className={vazirmatn.className}>
        <MainProviders theme={theme?.value as ThemeType}>
          <main>
            <div className='root'>{children}</div>
          </main>
        </MainProviders>
      </body>
    </html>
  );
}
